### ISSUE TITLE
Graphical glitch: Single BB crafting table

### ISSUE THREAD

**Issue by foxanthony1** [einsteinsci/betterbeginnings#104]
When I place a single BB crafting table and right click it, the crafting gui shows for a split second and then it disappears. No other problems - just the crafting table isn't usable. The vanilla table works fine and the A.C.T. table is also fine.

I'm using MultiMC with forge-1.8-11.14.4.1563 and betterbeginnings-MC1.8.0-b0.9.5-R5a. No other mods.

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Linux (amd64) version 3.13.0-24-generic
	Java Version: 1.8.0_66, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1230263968 bytes (1173 MB) / 1622671360 bytes (1547 MB) up to 3937402880 bytes (3755 MB)
	JVM Flags: 2 total; -Xms1280m -Xmx4224m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 346.96' Renderer: 'GeForce GTX 750 Ti/PCIe/SSE2'

**Comment by knoxx093** [comment]
@foxanthony1 thanks for the report, this glitch has been fixed for next release.
commit 2960dd0

**Comment by foxanthony1** [comment]
Great1
