### ISSUE TITLE
[Enh] Rabbit Hide makes leather strip(s)

### ISSUE THREAD

**Issue by knoxx093** [einsteinsci/betterbeginnings#105]
I know vanilla lets you craft 4 hides into a leather, but perhaps BB should let you make a single leather strip per 1-2 hide or some such.

I've had multiple testing worlds where I've found many rabbit before finding a single cow.

Is there a better spot to put suggestions/ideas?

**Comment by einsteinsci** [comment]
I like that idea as a shortcut to leather strips. Should be very easy to implement.

BetterBeginnings has a Trello board which we use to decide on what features to add, how to add them, and how to split them across versions. Currently there's only 3 team members, myself, AnonTheMouse, and Leviathan143. Iliminate would be added if he still had time to work on BB. Anybody who helps out with this mod long enough will find themselves part of the team.

**Comment by knoxx093** [comment]
52b04968
