### ISSUE TITLE
Items Duplicate when shift-clicked from certain spot

### ISSUE THREAD

**Issue by knoxx093** [einsteinsci/betterbeginnings#107]
To Reproduce:

1) Place item to duplicate in the farthest right slot on the hotbar.
2) Ensure there are no other stacks of same item anywhere in inventory.
3) Open the Brick Oven interface.
4) Shift-click the item to duplicate.
5) Item stack will appear in inventory with 2x stacksize

Notes: I'm not sure if this issue exists with the other brick oven. Have confirmed it does not occur when using the smelter, kiln, or double workbench.

**Comment by einsteinsci** [comment]
Sounds like a bug in the `Container.transferStackIntoSlot()` (or whatever it's called) code. I'll take a look at it when I get home.

**Comment by einsteinsci** [comment]
Does this occur in 1.7.10?

**Comment by einsteinsci** [comment]
It was an off-by-one error on [ContainerBrickOven Line 133](https://github.com/einsteinsci/betterbeginnings/blob/main/src/main/java/net/einsteinsci/betterbeginnings/inventory/ContainerBrickOven.java#L133).
