### ISSUE TITLE
Yet another crash

### ISSUE THREAD

**Issue by zHawky** [einsteinsci/betterbeginnings#114]
Hello fellows, i guess nei unnecessary for playing with mod, because when im look through the food cook recipes it give me a crash, am i doing wrong?
Im even disable all of modules, that dont work :(
http://pastebin.com/eL9x0nLi

**Comment by einsteinsci** [comment]
This is a known bug with NEI. I have no idea why it happens, but it occurs occasionally. I've never experienced this myself, but it seems that it only occurs once and then goes away.

**Comment by knoxx093** [comment]
@einsteinsci  Why is NEICampfireRecipeHandler importing "scala.actors.threadpool.Arrays" instead of using "java.util.Arrays" ? Am I missing something or could this be causing awkward behavior?

**Comment by einsteinsci** [comment]
Probably because I hit tab on the wrong thing. I don't know why IntelliJ keeps pointing me to Scala libraries, but that's what's causing this.

I'm trying to push a commit, but for some reason only my browsers seem to be able to access the internet today.

**Comment by knoxx093** [comment]
I popped up #115, has one additional change because eclipse doesnt like sending List&lt;Object&gt; into a function instead of List&lt;PositionedStack&gt;

**Comment by einsteinsci** [comment]
Fixed in commit 51dc7b809fd4d53af5a7a9e9ff2ee9411394f94b.
