### ISSUE TITLE
Crash upon piston use in multiplayer with Optifine.

### ISSUE THREAD

**Issue by n49o7** [einsteinsci/betterbeginnings#119]
The game crashes if a player near me uses a piston or if I use one myself. Sticky or normal. Local or server. Forge -1577 or -1563. It's a good mod! Keep it up.

[logs.zip](https://github.com/einsteinsci/betterbeginnings/files/111580/logs.zip)

**Comment by einsteinsci** [comment]
Are you sure this is caused by BetterBeginnings and not a one-time random glitch (possibly caused by another mod)? In the stacktrace it says the piston's TESR* had an exception, which has nothing to do with BB at all. BB only has one TESR, and that's for the Repair Infusion table. I don't touch the piston code in any way.

*TESR = Tile Entity Special Renderer

**Comment by n49o7** [comment]
I should have given more details.
Initial troubleshooting gave me these results:

- No Forge: no crash
- Forge without any mods: no crash
- All mods except BetterBeginnings: no crash
- All mods with BetterBeginnings: crash
- BetterBeginnings alone: crash

It's weird for sure. I was thinking it could be something in Minecraft 1.8 that somehow got aggravated by BetterBeginnings. Sounds like voodoo to me.

**Comment by n49o7** [comment]
Something more interesting: without BetterBeginnings but with other mods, the piston block flickers when I pull the lever. I'm testing each mod now.

**Comment by n49o7** [comment]
Ok, it's OptiFine. I'm using _1.8.0_HD_U_H2 but users have reported this bug since B4. It's interesting that it should just cause flicker with OptiFine alone but crash the game if run with BetterBeginnings. So, voodoo after all.

**Comment by einsteinsci** [comment]
Good to know. Probably a class file conflict. I want to make sure BB is compatible with OF as much as possible, but apparently there's nothing I can do here.

**Comment by n49o7** [comment]
Yup. For the sake of doing things right I'd like to point out that it's not specifically a multiplayer issue. Sorry about all those notifications.
