### ISSUE TITLE
campfire doesnt work and everything else does

### ISSUE THREAD

**Issue by SalvadorSlX7** [einsteinsci/betterbeginnings#121]
any ideas on fix

**Comment by Leviathan143** [comment]
How did you try to light it? This issue has been reported several times and every time it was user error.

**Comment by einsteinsci** [comment]
I probably need to add "How do I light the campfire?" to the FAQ.

**Comment by SalvadorSlX7** [comment]
with the fire bow

________________________________

**Comment by einsteinsci** [comment]
I don't know what you're saying. Could you please provide a step-by-step or video of what you did to try to light the campfire?

**Comment by SalvadorSlX7** [comment]
My computer is broken.

Sent from Outlook<http://aka.ms/f818qx>



On Sun, Feb 21, 2016 at 3:37 PM -0800, "sealed interface" <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't know what you're saying. Could you please provide a step-by-step or video of what you did to try to light the campfire?

-
