### ISSUE TITLE
Advanced Crafting Table Issues

### ISSUE THREAD

**Issue by Shadows-of-Fire** [einsteinsci/betterbeginnings#124]
Any of those advanced crafting methods in the Advanced Crafting Table cause this crash
https://gist.github.com/Shadows-of-Fire/d1d449669469900701f816c59fcca47d
They also cause the items that have those methods applied to them to not render at all in the workbench, like they were not part of the recipe.

**Comment by Shadows-of-Fire** [comment]
Similarly, the catalysts section does not support ore dictionary entires.

**Comment by einsteinsci** [comment]
I think I remember @Leviathan143 saying that transforms aren't supported.

**Comment by Shadows-of-Fire** [comment]
Yeah, running into other issues, running transformDamage on ore:itemKnife (or otherwise any betterbeginnings:materialKnife) causes it to duplicate.

**Comment by Shadows-of-Fire** [comment]
To further this, it seems to only occur of items on the itemKnife oredict.  The flint hatchet has no such issue.

**Comment by Shadows-of-Fire** [comment]
More issues with itemKnife, using it in any recipes (without transform damage) and even the default recipes in an Advanced Crafting Table causes it to remain at 0 durability and never destroy itself.

**Comment by Leviathan143** [comment]
Transforms are not supported at this time, so don't use them, anything from [here](http://minetweaker3.powerofbytes.com/wiki/Tutorial:Advanced_Recipes#Output_reuse_and_transformations) won't work. I can look into the other issues if you provide me a copy of the problematic scripts.

**Comment by Shadows-of-Fire** [comment]
`AdvancedCrafting.addRecipe(<TConstruct:ToolStationBlock:1>, [[<ore:plankWood>, <betterbeginnings:leatherStrip>, <ore:plankWood>], [<ore:logWood>, <TConstruct:blankPattern>, <ore:logWood>], [null, null, null]], [<ore:itemString> * 4]);`

This is resulting in the ore:itemString not being shown in the catalysts for nei.
On a side note, putting thread into the ACT just crashed me with this:
https://gist.github.com/Shadows-of-Fire/266568916eb2b8076e0725e507ad0fcb
FML Log: https://gist.github.com/Shadows-of-Fire/641234a22945156f46fc8a71d5bd588a

**Comment by Shadows-of-Fire** [comment]
However,
`AdvancedCrafting.addRecipe(<TConstruct:ToolStationBlock>, [[<ore:itemString>, <ore:plankWood>, <ore:itemString>], [<ore:logWood>, <TConstruct:blankPattern>, <ore:logWood>], [null, null, null]], [<minecraft:stick> * 8]);`
works perfectly fine.  It seems that catalysts have problems with oreDict.

**Comment by Leviathan143** [comment]
Thanks, I can onto debug and fix this now.

**Comment by Shadows-of-Fire** [comment]
`AdvancedCrafting.addRecipe(<TConstruct:ToolStationBlock>, [[<ore:itemString>, <ore:plankWood>, <ore:itemString>], [<ore:logWood>, <TConstruct:blankPattern>, <ore:logWood>], [null, null, null]], [<minecraft:stick> * 8]);`
Is causing the crash https://gist.github.com/Shadows-of-Fire/715c0a08bd82bb456ab4bdd78e220e46
This is before i even get to adding the catalyst items, crashing right as the last of the crafting reagents is added to the 3x3 grid.  This crash is different from the other two, but they are still all render related.

**Comment by Leviathan143** [comment]
Apparently MT uses a different class when the OreDict entry is a stack instead of a single item. This other class does not have the methods I need for it to be useful. There's a workaround, but I don't like it.

**Comment by Leviathan143** [comment]
@Shadows-of-Fire 
I've patched the issues. Transforms are still unsupported, and may have odd results. I will be implementing them sometime in the future if it is possible. Once einsteinsci builds a new version, you'll be good to go. Thanks for reporting this to us and waiting patiently for a fix.

@einsteinsci 
For future reference, posting Forge events does not do anything but post the event. The pre-processing is done in a method in ForgeHooks or ForgeHooks client.

**Comment by einsteinsci** [comment]
Fixed by [1.7.10 PR #4](https://github.com/einsteinsci/betterbeginnings-MC1.7/pull/4), aside from transforms.

@Leviathan143 Ok. Not entirely sure what that's related to, but interesting.
