### ISSUE TITLE
Null Pointer Exception in GuiKiln

### ISSUE THREAD

**Issue by UndeadZeratul** [einsteinsci/betterbeginnings#127]
[Crash Report](https://github.com/UndeadZeratul/ThereWillBeBlood/issues/146)
[Related Line](https://github.com/einsteinsci/betterbeginnings-MC1.7/blob/6a5da339d7df93e75a02789154ea950f61acbe44/src/main/java/net/einsteinsci/betterbeginnings/gui/GuiKiln.java#L49)

It looks like the related Tile Entity was null and therefore the isBurning() method couldn't have been accessed; there probably just needs to be a null check beforehand.  Only problem is, I'm unsure as to how to recreate this, since this was a crash report sent to me by YAMPST.

**Comment by einsteinsci** [comment]
I'm not familiar with YAMPST. Is it specific to dedicated servers?

**Comment by UndeadZeratul** [comment]
It's not specific to servers, you can download the pack tracker jar to clients as well, which is the version that threw the error (I split up my trackers to each launcher the client is deployed on as well as a separate tracker specific to servers).

It's strange that it's throwing an error in a method you don't change, yet it also says it's happening on the line I referenced, which is a method you did alter, and at a place which makes sense to throw an NPE.

From the crash report, it looks like the client was running v0.9.5 R7, which was the most recent version when I compiled the pack together for the release, did anything change in that code since that version?

From the crash report: ```betterbeginnings{0.9.5-R7} [BetterBeginnings] (betterbeginnings-MC1.7.10-b0.9.5-R7.jar)```

**Comment by Leviathan143** [comment]
@UndeadZeratul 
It should be impossible for the TE to be null at that line, GuiKiln is only constructed in one place, and the kiln TE should never be null there either. Does TWBB have anything like Transvector Interfaces or Autonomous Activators?

**Comment by UndeadZeratul** [comment]
No, I've actually stayed away from automation and fake players.  I'm not familiar with Transvector Interfaces, but if they're the things that wirelessly interact allowing more than just 6 blocks to interact with a singular machine, then no I don't have the mod that adds that in the pack.

Thermal Foundation is included, but Thermal Expansion is not, so Tesseracts and Autonomous Activators are both out as well.  I don't know of any other machines/blocks in the pack that allow for fake player interaction or remote access, either.  I did notice this crash report has two new mods added to it that I don't deploy with: Fastcraft v1.23 and JourneyMap v5.1.3-unlimited.  Had I known fastcraft was included I'd be a bit more wary about reporting this, because it's known to cause odd behavior, but at the same time it's not in any of the stacktraces; neither is journeymap, for that matter.  Would either of these cause the issue even though they don't seem to be included along the logical path?

**Comment by Leviathan143** [comment]
@UndeadZeratul
No, I don't think so, AFAIK Fastcraft changes the trig functions Minecraft uses. I have a few suspicions to investigate.

**Comment by einsteinsci** [comment]
@Leviathan143 @UndeadZeratul Did either of you find anything that might cause this? If not, I think I'll have to close it as I've had no other reports of this.

**Comment by Leviathan143** [comment]
@einsteinsci I never got round to checking it out, it didn't seem particularly important as there was only one occurrence.

**Comment by einsteinsci** [comment]
Closing it then.
