### ISSUE TITLE
Crash on Campfire Recipe lookup in NEI

### ISSUE THREAD

**Issue by rckymtnrfc** [einsteinsci/betterbeginnings#130]
I was looking up recipes in NEI and when I clicked over to the Campfire recipes, I'm seeing the following crash on the client.

http://pastebin.com/aaRnhFSA

Forge 1614, BB 0.9.5-R7

**Comment by rckymtnrfc** [comment]
Sorry, known issue, #114

**Comment by einsteinsci** [comment]
That was fixed a long time before R7, which may have only been an issue for the 1.8 branch. Does this reliably happen still?

**Comment by rckymtnrfc** [comment]
Yes, it's happening repeatedly. I saw you mentioned it would happen once and then stop but I'm seeing it every time.

**Comment by einsteinsci** [comment]
I just tested this myself in the dev environment and I can't recreate it. Does this happen when BetterBeginnings and NEI (and their dependencies) are the only mods installed?

**Comment by Leviathan143** [comment]
@einsteinsci 
It was patched on the 1.8 branch, but never on the 1.7.10 branch

**Comment by rckymtnrfc** [comment]
I did see another crash with the same scala error, perhaps it's already fixed but it occurs when adding custom shapeless recipes to the Oven via Minetweaker.  Sorry, I overwrote the log file so I don't have the specifics but I can recreate it you want.  Work around is just to use shaped recipes, since it's a single item input, still works like a shapeless recipe..

**Comment by einsteinsci** [comment]
I just realized you meant recipes that are done in the campfire, not the recipe itself. Bug is about to be fixed.

**Comment by einsteinsci** [comment]
Fixed in [latest commit](https://github.com/einsteinsci/betterbeginnings-MC1.7/commit/2ce0e320b13fad45b0fffde846f49acee32920f0). The bug will be fixed on R8.

**Comment by Leviathan143** [comment]
You need to patch OvenTweaker as well, I accidentally imported a scala class there too.

**Comment by einsteinsci** [comment]
[Fixed](https://github.com/einsteinsci/betterbeginnings-MC1.7/commit/5fbe7671ff9d0ab538c7233a6d3efd22eba0d922). For real now.
