### ISSUE TITLE
Fuel tooltip does not update

### ISSUE THREAD

**Issue by einsteinsci** [einsteinsci/betterbeginnings#131]
The fuel level tooltip (and the power level tooltip on the WIP powered furnaces) does not update when fuel depletes. When fuel/power is added, the tooltip updates, but still remains out of sync, as it adds to the client-side value rather than re-syncing with the server-side one.

This used to work, but for some reason not anymore.

**Comment by einsteinsci** [comment]
Thanks a lot, GitHub automatic issue closer.

**Comment by Leviathan143** [comment]
What mod are you using to test this?

**Comment by einsteinsci** [comment]
@Leviathan143 What do you mean? This happens in my regular dev environment: BB, CCC, and NEI.

**Comment by Leviathan143** [comment]
How are you testing the powered furnaces with no RF generator?

**Comment by Leviathan143** [comment]
I've managed to find a way to reproduce this consistently. It only happens when the furnace is lit and the GUI hasn't been closed since it was lit. If you close and reopen the GUI, the tooltip works properly.

**Comment by Leviathan143** [comment]
No fix yet, but I have realised that the packets aren't threadsafe. 1.8 does networking on a separate thread, so you need to use Minecraft#addScheduledTask/MinecraftServert#addScheduledTask to affect things on the main thread.

**Comment by einsteinsci** [comment]
@Leviathan143 I've been testing this by setting the default power level to a few thousand RF via the constructor. I tested adding power by (temporarily) allowing a baked potato to be allowed into the battery slot.

**Comment by einsteinsci** [comment]
The issue still occurs when you put an item in and watch it go, but if you close the inventory between putting the item in and it being actually smelted, the issue does not occur.

**Comment by einsteinsci** [comment]
I fixed it by overriding the following methods in the container classes:

* `addCraftingToCrafters(ICrafting)`
* `detectAndSendChanges()`
* `updateProgressBar(int, int)`

**Comment by Leviathan143** [comment]
@einsteinsci Excellent! We should still make the packets threadsafe though.

**Comment by einsteinsci** [comment]
I'm not sure what that involves. So far the only packets are the Nether Brick Oven fuel, and the Campfire state (off/burning/decaying).

**Comment by Leviathan143** [comment]
@einsteinsci 
[Here](https://github.com/Leviathan143/Crafting-Utilities/blob/master/src/main/java/com/leviathan143/craftingutils/common/packets/PacketUpdateIngredients.java) is an example of a thread safe packet. You might also want to look at the [Forge docs](http://mcforge.readthedocs.io/en/latest/networking/simpleimpl/) for SimpleImpl.
