### ISSUE TITLE
1.7.10 Campfire does not recognize twilight forest meats

### ISSUE THREAD

**Issue by wizard1399** [einsteinsci/betterbeginnings#134]
Hey,

The campfire in the 1.7.10 version does not recognize venison or meef as foods that it can cook. I had to add these manually using minetweaker. Just wanted to let you know in case you needed to add in a workaround for these items.

**Comment by Leviathan143** [comment]
1.7.10 has no autoloader, and it will not be getting one, use Minetweaker. Development is currently focused on 1.8, once BB 1.0 has been released, we will begin work on 1.10/1.11.

**Comment by einsteinsci** [comment]
As long as meef and venison (and their cooked versions) inherit from `ItemFood`, the auto-loader will do all the work for you. Of course it'll be configurable after first-time setup.
