### ISSUE TITLE
NEI Integration for Rock Hammer

### ISSUE THREAD

**Issue by wizard1399** [einsteinsci/betterbeginnings#135]
Hey,

Could you possible add NEI integration for the rock hammer? It would be nice to know what the results will be when using the rock hammer on different things. This would also be handy since pack devs can add in rock hammer recipes using minetweaker.

**Comment by Leviathan143** [comment]
No, the 1.7.10 branch is only receiving bug-fixes, development is focused on BB for 1.8.

**Comment by einsteinsci** [comment]
I may add Rock Hammer JSON config options, which will likely make it into MineTweaker compatibility for 1.8 once that's a thing.
