### ISSUE TITLE
NEI report incorrect advanced crafting

### ISSUE THREAD

**Issue by wizard1399** [einsteinsci/betterbeginnings#136]
Hello,

I am using vers 1.7.10-b0.9.5-R7 which is the most current version on curseforge at the time of writing this. Many of the items for advanced crafting have a mismatch between what NEI says is needed and what the actual advanced crafting table says it needs. I went through the list you have posted on the wiki and the following items have a recipe mismatch:

cauldron, brewing stand
bed
piston
compass, clock
hopper
fence gate
redstone lamp
dropper, dispenser
chest, trapped chest
powered rail, activator rail, detector rail, minecart
iron door
note block, jukebox
tnt
anvil

Also, you have the redstone comparator listed as needing advanced crafting, but it has no catalysts.

**Comment by Leviathan143** [comment]
b0.9.5-R7a is the latest version on CF. Test with that.

**Comment by Leviathan143** [comment]
Upon investigation, it seems that catalyst stacksizes are not displaying correctly in NEI. The comparator recipe has a typo.

**Comment by wizard1399** [comment]
Great. Sounds like you know where the root of the issue is. Will there be a fix possible? I have also noticed that some recipes don't use all of the catalyst up. (ex hopper)

**Comment by Leviathan143** [comment]
@wizard1399 
It's been patched, the patch will be in the next release.

**Comment by wizard1399** [comment]
:) Thanks. Keep up the good work.
