### ISSUE TITLE
Curse Launcher cannot find BetterBeginnings

### ISSUE THREAD

**Issue by UndeadZeratul** [einsteinsci/betterbeginnings#139]
I'm having trouble getting the Curse Launcher to find project 230120, which is BetterBeginnings, when I try to install my modpack on it.

When trying to install versions 1.0.0 or 1.1.0 of TWBB on the curse launcher, I get a "Exception of type 'Curse.Radium.InstallManagement.InstallTaskFailedException' was thrown." message.  Upon looking into the logs, I found [this](http://pastebin.com/rmjNZFdF).  The only thing I can think of, is because your mod is listed as experimental, Curse doesn't sync it across the network, and thus the launcher doesn't download it.

I've tried setting the pack profile to prefer betas, I've even tried setting Curse to prefer betas.  It still can't seem to find your project.  What I don't get is why this wasn't an issue for v1.0.0 before, and yet now when I try to install that version, I get the same error as v1.1.0.

If you were to mark both 0.9.5 R7 and 0.9.5 R7a for 1.7.10 as releases, would that fix the Curse Launcher having issues downloading the mod?

**Comment by Leviathan143** [comment]
@UndeadZeratul I've marked 0.9.5 R7a as release. Tell me if that fixes the issue.

**Comment by UndeadZeratul** [comment]
I just tried it and got the same error...  I'll try again later, as maybe it hasn't had a chance to propagate across the Curse Network yet?

**Comment by Leviathan143** [comment]
@UndeadZeratul 
It's not localised to you either, I just tried and got the same error.

**Comment by UndeadZeratul** [comment]
That's very strange, indeed.  I've gone ahead and submitted a bug to Curse via the launcher, so maybe they can shed some light on this situation.

If you guys find out anything on your end, let me know.

**Comment by TehNut** [comment]
Just dropping in to mention that as discussed [here](https://www.reddit.com/r/feedthebeast/comments/52hlfv/fellow_modpack_developers_have_any_of_you_run/), this issue is caused by the project being marked as experimental.

**Comment by Leviathan143** [comment]
@TehNut Thanks, but we're aware of that. u/Daomephsta is my reddit account.

**Comment by Leviathan143** [comment]
@UndeadZeratul Can you please close this? I can't for reasons explained in #147

**Comment by UndeadZeratul** [comment]
Sorry for the late reply, I can certainly close this issue.
