### ISSUE TITLE
1.7.10 Recipe issues: advanced crafting bench, brick oven

### ISSUE THREAD

**Issue by Langusteer** [einsteinsci/betterbeginnings#140]
Some of the tool recipes does not do what they are supposed to
The advanced crafting bench recipes for iron pickaxe show up with 3 leather strip as catalysts yet only 1 strip is used when crafting the pickaxe. Similiar issues with other tools through out the mod.

This can not be adjusted with minetweaker. Using the functions in MT as following: 

`AdvancedCrafting.removeOutput(<minecraft:iron_pickaxe>);
AdvancedCrafting.addRecipe(<minecraft:iron_pickaxe>,
[
[<minecraft:iron_ingot>, <minecraft:iron_ingot>, <minecraft:iron_ingot>],
[null, <minecraft:stick>, null],
[null, <minecraft:stick>, null]
]
, [<betterbeginnings:leatherStrip> *2]);`

The iron pickaxe recipe still uses up 1 leather strip.

I've not been able to isolate the two issues (minetweaker not doing what it supposed to, and better beginnings recipes not functioning correctly)

**Comment by einsteinsci** [comment]
Does this happen with normal (non-minetweaker) recepies?

**Comment by Leviathan143** [comment]
I've successfully reproduced this and I am currently debugging the issue.

**Comment by Leviathan143** [comment]
More info on the issue.
It only occurs if there are not enough materials in the crafting grid to make multiple outputs. As long as multiple outputs can be made, the recipes work correctly.

**Comment by wizard1399** [comment]
There was a similar issue a while ago that I reported. Most of the advanced crafting recipes were not being reported correctly to NEI. I'll see if I can find the issue number to reference it here.
