### ISSUE TITLE
Iron nuggets from some mods dont get consumed when crafting.

### ISSUE THREAD

**Issue by TheCorruption** [einsteinsci/betterbeginnings#142]
tested on 0.9.8-R2c, nuggets from Embers get consumed, but not immersive engineering or better with mods.

**Comment by Leviathan143** [comment]
This repo is inactive as I do not have the necessary perms to handle issues properly here. einsteinsci is currently busy IRL, so I am maintaining the mod. Please report issues on [my fork](https://github.com/Leviathan143/betterbeginnings-MODIFIED), where I can handle them properly.

**Comment by Leviathan143** [comment]
I've just tracked down the problem and fixed the bug, it'll be in the next release.

**Comment by TheCorruption** [comment]
Ok then, thank you.
