### ISSUE TITLE
There is a conflict with ExtraUtils2(1.10.2)

### ISSUE THREAD

**Issue by Xiaoyan366** [einsteinsci/betterbeginnings#143]
There is a conflict with ExtraUtils 2
The following is an error report
[crash-2017-01-11_21.19.14-client.txt](https://github.com/einsteinsci/betterbeginnings/files/698969/crash-2017-01-11_21.19.14-client.txt)
Version: betterbeginnings-MC1.10.2-b0.9.8-R2c

**Comment by Leviathan143** [comment]
Please close this issue and recreate it on [Leviathan143/betterbeginnings-MODIFIED](www.github.com/Leviathan143/betterbeginnings-MODIFIED)
