### ISSUE TITLE
Crash while picking up Kiln [b0.9.8 R2c]

### ISSUE THREAD

**Issue by buymytoasters** [einsteinsci/betterbeginnings#144]
Looks like a tile freak-out with the Kiln. I noticed it when crafting one to place, picking one up, and when breaking a kiln. 

Absolutely loving this mod on 1.10.2 btw. Been working on a private pack centered on hardcore survival and this fits perfectly. Thank you for taking the time to create BB.

Forge: 1.10.2-12.18.3.2185
Minecraft Version: 1.10.2
Operating System: Linux (amd64) version 3.16.0-4-amd64
Java Version: 1.8.0_111, Oracle Corporation

http://pastebin.com/3tBtzkWn

**Comment by Leviathan143** [comment]
Please close this issue and recreate it on Leviathan143/betterbeginnings-MODIFIED

**Comment by Leviathan143** [comment]
@buymytoasters I've moved this issue to Leviathan143/betterbeginnings-MODIFIED#15
I still want you to close this issue though, as I cannot for reasons explained in #147.

**Comment by buymytoasters** [comment]
Can do after work today. Thank you for taking a look.
