### ISSUE TITLE
[1.7.10] Bypass advanced crafting recipes with BoP materials

### ISSUE THREAD

**Issue by syndicate25** [einsteinsci/betterbeginnings#145]
Advanced crafting can be bypassed completely when using any wood type from Biomes O' Plenty.

A few things I tested were doors, fence gates, and chests. All can be made in the better beginnings double workbench/table, without putting the materials in on the left side. They show that they're required, but they aren't. They still are required when using any vanilla wood, though.

**Comment by Leviathan143** [comment]
Please close this issue and recreate it on [Leviathan143/betterbeginnings-MC1.7](www.github.com/Leviathan143/betterbeginnings-MC1.7)
