### ISSUE TITLE
[1.7.10] Missing textures

### ISSUE THREAD

**Issue by syndicate25** [einsteinsci/betterbeginnings#146]
The textures for the two marshmallows on a stick are missing. 

[http://i.imgur.com/qZO4e31.png](url)
[http://i.imgur.com/JBPnY68.png](url)

**Comment by Leviathan143** [comment]
Please close this issue and recreate it on [Leviathan143/betterbeginnings-MC1.7](www.github.com/Leviathan143/betterbeginnings-MC1.7)
