### ISSUE TITLE
IMPORTANT NOTICE - DO NOT CREATE ISSUES HERE

### ISSUE THREAD

**Issue by Leviathan143** [einsteinsci/betterbeginnings#147]
I don't have the necessary permissions to maintain this repo, and I have been unable to contact einsteinsci to obtain them. Please create issues on [my fork](http://www.github.com/Leviathan143/betterbeginnings-MODIFIED). This repo is effectively dead, I will not check it for new issues.

**Comment by Leviathan143** [comment]
I don't have the necessary permissions to maintain this repo, and I have been unable to contact einsteinsci to obtain them. Please create issues on [this repo](www.github.com/Leviathan143/betterbeginnings-MODIFIED).

**Comment by WesCook** [comment]
Link to your fork is a 404.  You'll need `https://` in there as well.
