### ISSUE TITLE
Hoppers are pulling fuel out of kiln [1.10]

### ISSUE THREAD

**Issue by Divineaspect** [einsteinsci/betterbeginnings#148]
this makes using vanilla "automation" quite impossible.

**Comment by Leviathan143** [comment]
This repo is dead. DO NOT CREATE ISSUES HERE. The new repo is Leviathan143/betterbeginnings-modified. Please close this issue and recreate it there.

#147 is clearly visible on the issues page. It explains that this repo is dead, why it's dead and links to the new repo. I do not watch this repo, I only noticed this issue by chance.

Sorry if I sounded rude. I thought I'd fixed all of BB's issues, only to find that the dead repo had 7 issues on it, despite me doing my best to notify people that this repo is dead.
