### ISSUE TITLE
Update, rework, and redesign

### ISSUE THREAD

**Issue by einsteinsci** [einsteinsci/betterbeginnings#156]
* Update to 1.12. Mark as alpha until further notice.
* Rework most of the mod to be less intrusive into a modpack, and allow for greater compatibility.
* Redesign core features to fit closer to the vanilla playstyle without forcing it upon players.

**Comment by einsteinsci** [comment]
Re-creating in separate repository for smoother design under the name "BetterBeginnings Reborn". This repository will be closed off soon after the first alpha release.

**Comment by MagmaSlime123** [comment]
You have 5 issues. Please read them. If this mod is dead, please remove it.
