### ISSUE TITLE
[Suggestion]1.7.10 NEI support

### ISSUE THREAD

**Issue by FuYang001** [einsteinsci/betterbeginnings#157]
![111](https://user-images.githubusercontent.com/25576128/39391605-e70fe034-4ad8-11e8-9f60-547b38b7c4b0.png)
Could you add a support that clicking the red zone can list all of recipes in NEI gui the crafting table or kiln has? Many of other NEI support mods have this feature.

**Comment by UnlimatedStone9** [comment]
This would be incredibly useful, it has been driving me insane for the longest time trying to figure out what recipes exist in the mod by default so I can remove them

**Comment by einsteinsci** [comment]
Archiving long-abandoned project. If anyone wants to fix this, feel free to clone the project and continue development.
