### ISSUE TITLE
[Suggestion] Multitools

### ISSUE THREAD

**Issue by Gandalf360one** [einsteinsci/betterbeginnings#160]
Can you pls add an option where it is possible set an item as multitool ?
For Example:
- Mekanism: Atomic Disassembler
- Draconic Evolution: Draconic Staff of Power
- Matter Overdrive: Omni Tool
and more

**Comment by einsteinsci** [comment]
Archiving long-abandoned project. If anyone wants to implement this, feel free to clone the project and continue development.
