### ISSUE TITLE
Crash when crafting iron helmet

### ISSUE THREAD

**Issue by einsteinsci** [einsteinsci/betterbeginnings#51]
Possible crash when crafting iron helmet. Not yet confirmed or tested.

**Comment by Pablode** [comment]
Replace "ironNugget" with "nuggetIron" in RegisterRecipes.java, line 443. https://github.com/einsteinsci/betterbeginnings/blob/MC_1.8/src/main/java/net/einsteinsci/betterbeginnings/register/RegisterRecipes.java#L443

**Comment by einsteinsci** [comment]
That would be it. Thanks for finding that for me. It'll be fixed with the 1.8 release (v0.9.5).

It looks like I also need to have some error checking when I load recipes dynamically.

**Comment by einsteinsci** [comment]
Fixed in 1.8 version. Still present in 1.7.10.

**Comment by einsteinsci** [comment]
Fixed in 1.7.10 version.
