### ISSUE TITLE
Loading BetterBeginnings recipes from config file

### ISSUE THREAD

**Issue by Orangyfresh** [einsteinsci/betterbeginnings#54]
I'm wondering if its possible to change the crafting recipes of equipment added by Simple Ores to match the recipe style of Better Beginnings. In short, Simple Ores equipment has vanilla recipes and I was wondering if those recipes can be changed to require an advanced crafting table and catalysts. 

Is there a way for me to change the recipes myself, like a config file or is this something that would need to be integrated into the mod? 

If I can do it myself then that would be great, but if it needs to be implemented then don't worry too much about it. I know how many things you've got on your todo list already.

**Comment by einsteinsci** [comment]
This would require an API on my side, and then a way to load recipes via config. Both of those features are intended for the 1.0 release (quite a while away no thanks to 1.8).

**Comment by Orangyfresh** [comment]
Okay, I thought it might require an API. I'm glad to see that you've already thought of this. Will 1.0 be released for 1.7.10 as well?

**Comment by einsteinsci** [comment]
I don't believe so. Unfortunately, due to the complexity of creating and maintaining an API, this would be just too much work, and by the time I finish the API for the 1.8 version, 1.8 will be the standard version for Minecraft mods, so most of your mods will probably have updated (except for the ones that never will).

**Comment by Orangyfresh** [comment]
Fair enough man. Just keep the work simple. I really like what you're doing  so I hope everything goes to plan.

**Comment by einsteinsci** [comment]
JSON loading is complete aside from auto-loading, which will be released in 0.9.8.

**Comment by einsteinsci** [comment]
This and auto-loading is complete (although practically impossible to test). Closing issue(s).
