### ISSUE TITLE
name of object in adv. crafting

### ISSUE THREAD

**Issue by gogoghouha** [einsteinsci/betterbeginnings#55]
When transparent objects are displayed in the advanced crafting table, I think the name of these object  could appear when placing the mouse cursor on it.

**Comment by einsteinsci** [comment]
As these items aren't truly in there, and only rendered, I will need to create the tooltip from scratch, which would depend on if there's a forge hook for it, so this might not entirely be possible. Also, NEI support may eliminate the need for this feature.

**Comment by einsteinsci** [comment]
I've done this kind of thing with the Nether Brick Oven. Probably doable for the ghost items. Probably only going to show in 1.8 version.

**Comment by einsteinsci** [comment]
Should be fairly easy to implement.
