### ISSUE TITLE
Addon concept

### ISSUE THREAD

**Issue by gogoghouha** [einsteinsci/betterbeginnings#57]
hello,

I'm working on an addon for BetterBeginnings mod: it's a prototype for 1.7.10 with some bugs :/  .

Is it possible to know your plans (new features) for BB-1.0/1.1+ , so we don't have to implement some features twice ;) ? (Or eventually help each other ?)

**Comment by einsteinsci** [comment]
Unfortunately, my plan is for 1.7.10 to end at 0.9.5, roughly the same as it is currently. I'm a student so I don't have much time, and iLiminate left to work on other things a few months ago. The only additions I plan to add to 1.7.10 are compatibility-related, starting with NEI and a more modular config. I might create an API for 1.7.10, but probably not.

However, I have a lot of plans for 1.8, including several multiblock structures, expanding apart from just the whole three-furnaces thing. Some of the features will be included in 1.0, some in 1.1. Nonetheless, compatibility and modularization will be top priority after the 1.8 update (which will be almost entirely a port and nothing more at first), including an API for addons. Only after those are done will new features be added.

As I have worked on this mod, I have always planned for 1.7.10 to never get further than the beta stage; 1.8 was always the intended target for the complete and full-fledged mod.

I strongly suggest you save yourself a lot of trouble and wait for the 1.8 update before setting up connections to this mod.

**Comment by gogoghouha** [comment]
Fine, but I think I didn't explained my 'problem' very well :/ (sorry for my bad English)

- Because your mod is open source, we don't need an API. So don't worry about that.

- The add-on prototype (no name yet :p) is already written in 1.7.10 with BB-0.9.0 and works fine. My bugs are not BB-related.  And I'm of course waiting for a 1.8-update :D

- The prototype adds:
  1) contents such as tin, copper, bronze, steel (more to come: it's only a prototype) with corresponding tools and armour
  
  2) some tweaks such as changing the harvest level of vanilla tools and blocks, as done in Iguanas Tinkers Tweaks. 

  I think you may be interested in this to eventually replace your event-based cancel-able blocks (which are sometimes buggy). They (and I) make use of reflection and this works fine for harvest levels (but changing durability doesn't work properly yet :/ , I have to check it out).

- I'm ALSO planning to add multi-blocks structures such as a forge, a big (alloy) smelter, big kiln , ...
  where the forge is used to make full metal tools (basically more durable) and adv. armour (more durable, potion effects) in a adv-crafting way.
  
-->So I'm simply curious what multi-blocks you will add :p

PS: I'm also student, who learned Java by modding tutorials ;) . So I don't have much time too, at least these 2 following months.

PPS: interesting links (1.7.x):
- Iguanas Tinkers Tweaks code https://github.com/SlimeKnights/IguanaTweaksTConstruct/tree/master/src/main/java/iguanaman/iguanatweakstconstruct/harvestlevels 
- reflection http://www.minecraftforum.net/forums/mapping-and-modding/mapping-and-modding-tutorials/2151027-1-7-x-using-reflection-to-modify-vanilla-values
- multi-blocks structures https://lomeli12.net/tutorials/tutorial-how-to-make-a-simple-multiblock-structure/

**Comment by einsteinsci** [comment]
Looks like the ideas you have in mind aren't any of the ones I have in mind for 1.1.0, so they would work very well in an addon. I do plan for most automation to come involving water-and-packed-ice conveyor belts, and for BB to encourage players to set those up. 1.1.0 will have a few automation-oriented features, but it will mostly encourage automation to be largely the same as in vanilla (hoppers, pistons, and a whole lot of redstone).

I would love to see that reflection-based block breaking algorithm you have in mind. You can see my current (event-cancelling) one in [BlockBreakHelper.java](https://github.com/einsteinsci/betterbeginnings/blob/MC_1.8/src/main/java/net/einsteinsci/betterbeginnings/event/BlockBreakHelper.java). So far it has fixed the whole obsidian and redstone not breaking bug.

**Comment by Leviathan143** [comment]
@gogoghouha Are you still interested in trying to make an addon for BB?
