### ISSUE TITLE
Knife has no restrictions on block breaking. [1.7.10]

### ISSUE THREAD

**Issue by dizzysoul** [einsteinsci/betterbeginnings#62]
Something seems to be mis-configured for the knife to where it's allowed to mine any block. For example, if you enable adventure mode, there are correct material restrictions on what can be mined with an axe, shovel, sword, etc. There are no restrictions on the knife, and it is allowed to mine any block.

This is a separate issue from the block restrictions you have programmed manually into the mod, and unfortunately these restrictions do not cover blocks added from other mods. New block types from other mods do have a material type which respects adventure mode restrictions, but the knife added by this mod is allowed to break any block type.

I'm not a mod developer, but this seems like a small change to change the item properties of the knife so that it behaves like a sword when it comes to block restrictions. I might try to fix this myself and submit a pull request.

This issue makes it impossible to restrict the player's tech progression when using other mods, as the knife allows players to mine any added block types.

Edit: I noticed that for the 1.7 build, on line 52 in itemKnife.java you have the following set to true:

    if (block.getMaterial() == Material.rock && toolMaterial.getHarvestLevel() >= 0)

and in the main branch you have this entire block of code disabled. Could this be the issue?

**Comment by einsteinsci** [comment]
Fixed from #53.
