### ISSUE TITLE
[Mod Suggestion/Question]: Minetweaker Support 

### ISSUE THREAD

**Issue by Lanse505** [einsteinsci/betterbeginnings#82]
Hello!

I'm working on a modpack that's possibly going to feature this mod, it's still in early alpha so many changes are abound. But my question at hand is do you have or are you planning to add Minetweaker support for your Windmill Grinder and Sluice? I'd love to incorporate this into my early-game of the pack.

**Comment by Lanse505** [comment]
Ignore This, Wrong Mod. I Derped Royally

**Comment by einsteinsci** [comment]
I actually am planning on adding Minetweaker-like support to this mod, but not directly through Minetweaker.
