### ISSUE TITLE
Galacticraft ores compatibility

### ISSUE THREAD

**Issue by Brickfix** [einsteinsci/betterbeginnings#85]
Ores from Galacticraft (tin, copper and aluminium ore) are all smelted into copper. Seems it is a meta-data issue, as all ore / ingots share the same block/item ID, only the damage value differs.
Happened on version 0.9.4-pre2

**Comment by Brickfix** [comment]
there is a fix to this as it is possible to craft the regular furnaces (as I found in your code), but it takes a bit away from the experience ...

**Comment by einsteinsci** [comment]
That's strange. Mod ores and ingot recipes are done through the ore dictionary. Either this method doesn't load damage values, or the ingots are incorrectly registered from Galacticraft's side.

**Comment by einsteinsci** [comment]
As my code calls Forge's code `OreDictionary.getOres()` (which returns a `List<ItemStack>`), it must be that Galacticraft doesn't register its ores with damage values. My code gets an itemstack, not just an item, so it can't be something on my end.

Does this occur with Thermal Expansion (which also uses damage values for ores and ingots)?

**Comment by einsteinsci** [comment]
Could someone else confirm this with just BB and Galacticraft?

**Comment by einsteinsci** [comment]
Since I've had no other instances of this happening, I'm going to close this issue.
