### ISSUE TITLE
Knives consumed in crafting at double workbench

### ISSUE THREAD

**Issue by einsteinsci** [einsteinsci/betterbeginnings#87]
When knives are used in crafting recipes at a double workbench instead of the player's 2x2 crafting grid, the entire knife is consumed rather than a durability point.

**Comment by Leviathan143** [comment]
Confirmed to happen in 1.8, not present in 1.7.10.

**Comment by einsteinsci** [comment]
Apparently this is present in 1.7.10.

**Comment by einsteinsci** [comment]
Fixed again.
