### ISSUE TITLE
Fix block-breaking algorithm (again)

### ISSUE THREAD

**Issue by einsteinsci** [einsteinsci/betterbeginnings#89]
Apparently the current algorithm is incompatible with blocks that break other blocks (BC quarries, etc.) I have to rewrite the whole d*** thing again to account for them.

**Comment by Leviathan143** [comment]
It's a 1 line fix.
In BBEventHandler#onBlockBreak() change
'BlockBreakHelper.handleBlockBreaking(e);'
to
'if (!(e.getPlayer() instanceof FakePlayer)) BlockBreakHelper.handleBlockBreaking(e);'

**Comment by einsteinsci** [comment]
I always thought fake players were an algorithm implemented by the modder, not a feature of Forge itself.

**Comment by einsteinsci** [comment]
Thanks to Leviathan143 for the fix.
