### ISSUE TITLE
OreDictionary catalysts are not consumed in advanced crafting

### ISSUE THREAD

**Issue by Tsyklop** [einsteinsci/betterbeginnings#91]
look this video https://youtu.be/06xF7lDSE9U

betterbeginnings-MC1.7.10-b0.9.5-R2b

**Comment by einsteinsci** [comment]
Oh... Gotta go fix that. Does this occur in the 1.8 version?

**Comment by einsteinsci** [comment]
Well that's weird. I don't see any reason for this to be happening. Is it Galacticraft that this is happening with, because from another Galacticraft-related issue, it seems Galacticraft doesn't use OreDictionary names correctly.

[Link to code that should work just fine](https://github.com/einsteinsci/betterbeginnings-MC1.7/blob/master/src/main/java/net/einsteinsci/betterbeginnings/register/recipe/AdvancedRecipe.java#L203)

**Comment by Tsyklop** [comment]
I do not play at 1.8. to version 1.8 is not the mods that were shown on the video.

And Galacticraft here with? If the nuggets of iron from other mods.

**Comment by einsteinsci** [comment]
I'm sorry, your English is very difficult to understand. Is Galacticraft included in the modpack? Are the iron nuggets shown in the video from Galacticraft?

Does this happen with iron nuggets from Thaumcraft or Tinker's Construct?

**Comment by Tsyklop** [comment]
Yes. included. Hm. I don't have iron nuggets from Galacticraft.

in the modpack there are no mods: Tinker's Construct and Thaumcraft. 
My ModList: http://pastebin.com/DUDxdWKw

**Comment by einsteinsci** [comment]
That's a lot of mods. With that many, there is a large chance one of those could be causing the problem. Could you try this with just BetterBeginnings and the mod whose iron nuggets were shown in the video?

**Comment by Tsyklop** [comment]
Yes, of course.

**Comment by Tsyklop** [comment]
@einsteinsci the same is happening.

**Comment by einsteinsci** [comment]
Which mod has the iron nuggets that are causing this problem? Which iron nugget mods did you have installed the first time?

**Comment by Tsyklop** [comment]
@einsteinsci Immersive Engineering, Thermal Expansion. 
No. no first time

**Comment by einsteinsci** [comment]
This one was a real pain to figure out.
