### ISSUE TITLE
java.lang.NoClassDefFoundError: scala/actors/threadpool/Arrays

### ISSUE THREAD

**Issue by Tsyklop** [einsteinsci/betterbeginnings#92]
Crash: http://pastebin.com/sBPWGdu8

I try look recipe cooked porkchop in the NEI

betterbeginnings-MC1.7.10-b0.9.5-R2b

**Comment by einsteinsci** [comment]
Just tested it myself and I'm not getting this, with pork or any of the cooked meats. It could have been a one-time crash with NEI, which can be buggy at times.
