### ISSUE TITLE
Tools marked as "drills" are not treated as tools

### ISSUE THREAD

**Issue by Tsyklop** [einsteinsci/betterbeginnings#93]
none the drill of mods not working. I'm trying to dig up the stone but I can not write that.
How fix this?

**Comment by einsteinsci** [comment]
I am not sure what you are saying. It is poorly translated. Which mod are you having trouble with? Did you try adding the items to the block breaking config options?

**Comment by Tsyklop** [comment]
look this -> https://youtu.be/FOKuyRFR6OQ

**Comment by Tsyklop** [comment]
so?

**Comment by einsteinsci** [comment]
That's really weird. Apparently this is happening with ProjectE tools as well. For some reason, setting a stick to be treated as a pickaxe works fine, but not ProjectE picks or GraviSuite (or I assume IC2) drills.

**Comment by einsteinsci** [comment]
Could you provide a pastebin link to the log?

**Comment by Tsyklop** [comment]
@einsteinsci https://gist.githubusercontent.com/Tsyklop/22a2a2cda345575321c2/raw/de98102ea10d271f5f1a835cce65aa2997c64246/Log%2520for%2520BB

**Comment by einsteinsci** [comment]
For some reason it can't find "GraviSuite:advDDrill". Are you sure that's the correct item id?

**Comment by Tsyklop** [comment]
![2015-11-17_10 46 34](https://cloud.githubusercontent.com/assets/6783568/11206563/97504820-8d18-11e5-8a82-3ec6d5f09a22.png)

`    # List of tools that should be treated as axes. Use this format: 'modid:itemName=toolTier' [default: ]
    S:"Also axes" <
        IC2:itemToolIridiumDrill=4
        GraviSuite:advDDrill=4
        rfdrills:redstone_drill=4
     >

    # List of tools that should be treated as pickaxes. Use this format: 'modid:itemName=toolTier' [default: ]
    S:"Also pickaxes" <
        IC2:itemToolIridiumDrill=4
        GraviSuite:advDDrill=4
        rfdrills:redstone_drill=4
     >`

dont work to

**Comment by einsteinsci** [comment]
Could you include a pastebin link to the log file for this one? I want to know if it can find the other drills as well.

**Comment by Tsyklop** [comment]
@einsteinsci https://gist.githubusercontent.com/Tsyklop/d61363e52663ed7b1a80/raw/ff82dcca1e50d62ec6369a7d4b9e6a65c004c794/gistfile1.txt

**Comment by Tsyklop** [comment]
so?

**Comment by einsteinsci** [comment]
This is going to be a tricky one to fix. It'll take a while to figure out what's going on internally.

**Comment by Leviathan143** [comment]
I have discovered the problem. The problem is that BB searches for the items during preinit, this is also when most mods register their items with Forge. Because of this BB cannot find items from any mod that loads after it.

**Comment by einsteinsci** [comment]
I think I know how to fix that.

**Comment by Tsyklop** [comment]
Drills from mod RFDrills don`t work....
`
        rfdrills:redstone_drill=4
        rfdrills:leadstone_drill=4
`

**Comment by einsteinsci** [comment]
Again, I need a log to figure out what's happening.

**Comment by Tsyklop** [comment]
@einsteinsci 
Log: https://gist.githubusercontent.com/Tsyklop/c73ac8f433896beece86/raw/0da4fbe78788daae5e730a66308a97ba5a7f3797/gistfile1.txt
Config: http://pastebin.com/rhKJep3X

**Comment by einsteinsci** [comment]
I found your problem:

```
[09:25:20] [Client thread/ERROR] [Better Beginnings/betterbeginnings]: No item found within 'IC2:itemToolIridiumDrill:1=4'.
[09:25:20] [Client thread/ERROR] [Better Beginnings/betterbeginnings]: No item found within 'GraviSuite:advDDrill:1=4'.
```

My config loads regular items (`net.minecraft.item.Item`), which do not store damage values. Damage values are stored in `ItemStack` objects. The config has no code to parse the `:1` suffix you added to indicate damage value. Since it seems from your config file you have already changed your config to remove the `:1` suffix, everything should work fine now.
