### ISSUE TITLE
Breaking ANY blocks generates a NullPointer Exception.

### ISSUE THREAD

**Issue by gblproduction** [einsteinsci/betterbeginnings#94]
When I load any world with the BetterBeginings Mod for Minecraft 1.8 (ONLY, working with 1.7.10),
then I break Any blocks, like Grass or Gravel, I get a NullPointer Exception.

If I stop Minecraft, remove the mod (It is the only mod installed), Relaunch Minecraft, load the SAME world, Everything is back to normal.

I am not getting the Loots of those blocks.
If I go Over a block that I broke, the player bounces like if the block was still there.
After Quitting & reloading the word, the blocks that I broke are still there.

For more details & Logs:
http://pastebin.com/A8Ri9dT9

**Comment by einsteinsci** [comment]
Could you provide a copy of your config file? I might be misinterpreting the config file.

**Comment by gblproduction** [comment]
BetterBeginnings config file? Here:
[betterbeginnings.cfg.txt](https://github.com/einsteinsci/betterbeginnings/files/42257/betterbeginnings.cfg.txt)

**Comment by einsteinsci** [comment]
I can't seem to replicate this in my dev environment. Not with my bare hands, with a block, with a regular item, or a tool. I can't replicate this with breaking grass, gravel, stone, dirt, snow, ice, or wood. Are you running on a dedicated server, or regular SSP?

**Comment by einsteinsci** [comment]
Release has been uploaded to CurseForge, and is awaiting approval.

**Comment by gblproduction** [comment]
I can confirm that the missing variable initialization fixed the problem.
Thanks!
