### ISSUE TITLE
Crash when using with buildcraft

### ISSUE THREAD

**Issue by spyspyyou** [einsteinsci/betterbeginnings#96]
The version b0.9.4-R2 somehow crahing when using it together with buildcraft 7.1.12.
I'm pretty sure it happenes when the buildcraft quarry tries to mine a block.

**Comment by einsteinsci** [comment]
This was fixed with v0.9.5. Update BetterBeginnings to the [latest version](http://minecraft.curseforge.com/projects/betterbeginnings-mod/files/2268357) and your problems will be solved.

**Comment by einsteinsci** [comment]
BetterBeginnings is still in beta on CurseForge, so mod updates do not come automatically. You'll have to update BB on your own in your modpack until I release BB 1.0.
