### ISSUE TITLE
Certain recipes do not work correctly with ProjectE installed

### ISSUE THREAD

**Issue by einsteinsci** [einsteinsci/betterbeginnings#97]
Specifically, recipes that use knives as ingredients.

If someone else could confirm this on 1.8 that would help.

**Comment by einsteinsci** [comment]
The recipes are still there, but ProjectE seems to make it so that recipes with wildcard values on tools no longer work as wildcard values.

**Comment by einsteinsci** [comment]
This might be a bug with Forge, could somebody test this with 1450, and just ProjectE and BB installed?

I probably should update to the latest 1.8 Forge version.

**Comment by knoxx093** [comment]
Something about interacting with projectE is causing the damage values coming back from the recipe to be 8 higher than what they should be. The wildcard items in recipes are being reported as damage value 32775 instead of 32767, and testing with a 0 registered is returning an 8 instead.

**Comment by knoxx093** [comment]
I believe this is a reported bug in ProjectE.

see: https://github.com/sinkillerj/ProjectE/issues/1111

Seems as if projectE calls getContainerItem on these ItemStacks which increments the itemDamage per ItemKnife.java

I tested this by overriding this fucntion for ItemKnifeFlint like so
```
	@Override
	public ItemStack getContainerItem(ItemStack stack)
	{
		return stack;
	}
```
which fixes the problem for the flint knife only

**Comment by einsteinsci** [comment]
@knoxx093 `getContainerItem()` is defined in `ItemKnife`, an abstract class that all knives inherit from:

```java
@Override
public ItemStack getContainerItem(ItemStack itemStack)
{
	itemStack.setItemDamage(itemStack.getItemDamage() + 1);
	return itemStack;
}
```

If we simply return the `ItemStack` we're given, without damaging it, the tool doesn't take any damage from crafting, which is the whole point of durability on the knives.

**Comment by knoxx093** [comment]
Yes that's exactly the problem. ProjectE's code is damaging the ItemStacks being used in recipes by calling getContainerItem on them. The point of my overriding that function for the knife was to make sure that is what was happening.

**Comment by einsteinsci** [comment]
It looks like all we can do is report this incompatibility on the ProjectE issue you mentioned earlier, and wait for sinkillerj to fix it.

**Comment by MaPePeR** [comment]
You could also fix this on your side by doing a 
```
if (itemStack.getItemDamage() == OreDictionary.WILDCARD...)  {
return itemStack;
}
```
i think.

Also i think this method is not supposed to change an itemstack, but return a changed copy... but i'm not sure about that..

**Comment by einsteinsci** [comment]
@MaPePeR It probably is supposed to return a changed copy. That actually might be why few other mods actually encounter this.

**Comment by einsteinsci** [comment]
If that commit didn't fix the issue, I'll need to put in that `if` structure @MaPePeR suggested. All it needs is a quick test.

**Comment by MaPePeR** [comment]
So the problem there is, that ProjectE uses `ItemStack`s directly from the `IRecipe`. It then used that `ItemStack` to check for `getContainerItem`. Because your `getContainerItem` modified the ItemStack it modified the `IRecipe` which broke the recipe.

Just an assumption....

ProjectE will still have problems 'reading' the recipe for emc calculation, but that problem is not on your side.

**Comment by knoxx093** [comment]
@MaPePeR @einsteinsci For future reference, using the Item class as a reference, it should return a new ItemStack.

**Comment by sinkillerj** [comment]
Thanks for the detective work guys, I looked around to see if I could find a issue in either codebase, but theres no way I was gonna catch this odd one.

**Comment by einsteinsci** [comment]
Could someone confirm if this still occurs?

**Comment by knoxx093** [comment]
@einsteinsci I've tested and haven't experienced this issue again since the fix.
