### ISSUE TITLE
Custom names do not persist after world is unloaded

### ISSUE THREAD

**Issue by Leviathan143** [einsteinsci/betterbeginnings#99]
Custom names do not persist for any furnace except the Nether Brick Oven. This was tested using BetterBeginnings 0.9.5 R5a with Forge 11.14.4.1563.

**Comment by einsteinsci** [comment]
Interesting. I wrote the code for my furnaces based on the vanilla furnace, so I'm not sure why this happens. Nonetheless, this should be a pretty easy fix; just make the block code read from the tile entity NBT and write when dropping the item stack.

**Comment by einsteinsci** [comment]
Apparently not an easy fix. The block drop code isn't explicitly written anywhere in `Block` (or anything that overrides), and I assume it's written in `World`. The `Block` code between the nether brick oven and kiln are essentially identical; I have no idea why names persist for it.

**Comment by einsteinsci** [comment]
Just tested this myself, and names *do not* persist for the Nether Brick Oven.

**Comment by Leviathan143** [comment]
> Just tested this myself, and names do not persist for the Nether Brick Oven. If they do for you, you must have fixed this bug during your cleanup for the N.B.O. and not the other furnaces.

 Nope, I reproduced the bug in vanilla BB before reporting it.

**Comment by einsteinsci** [comment]
@Leviathan143 Ah. That is a completely different issue, probably in the NBT load and save functions.

**Comment by einsteinsci** [comment]
Nothing wrong with the `readFromNBT()` and `writeToNBT()` functions, but I was able to recreate the actual problem.

**Comment by einsteinsci** [comment]
Does this happen in 1.7.10?

**Comment by einsteinsci** [comment]
This appears to still occur for 1.7.10.
